[package]
name = "helper-proc-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.89", features = ["full", "extra-traits"] }

[lib]
proc-macro = true

[dev-dependencies]
prettyplease = "0.2.25"